services:
  # Fastapi backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/app/backend/db
    networks:
      - app-network

  # Next.js frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge