version: '3'

services:
  # Fastapi backend
  backend:
    build: ./backend
    volumes:
      - ./backend/db:/app/backend/db
    # router traffic
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)" # Route traffic with /api to backend  
      - "traefik.http.services.backend.loadbalancer.server.port=8000" # Interval service port
    networks:
      - app-network

  # Next.js frontend
  frontend:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`jobdecoder.anubhavsamanta.tech`)"  # Route based on host domain
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - app-network

  # traefik reverse proxy
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.1
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80" # Listen on port 80
      - "--entryPoints.websecure.address=:443" # Listen on port 443
      # generate certificate
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=asamanta2123@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80" # HTTP port
      - "443:443" # The HTTPs port
      - "8080:8080" # The Web UI dashboard
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`jobdecoder.anubhavsamanta.tech`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    
networks:
  app-network:
    driver: bridge